---
alg: dalf
base_dir: log/dalf
log_level: INFO
gpu: 0
data:
  batch_size: 1024
  raw_dataset_dir: data/data_load_area.npz
  eval_batch_size: 1
  test_batch_size: 1
  len_data: 0.6
model:
  num_hours: 24
  # seq_len unit is day 
  seq_len: 30
  horizon: 1
  input_dim: 3
  verified_percentage: 0.8
  l1_decay: 0
  num_nodes: 29
  output_dim: 1
  rnn_units: 64
  num_rnn_layers: 2
train:
  dropout: 0
  epochs: 50000
  optimizer: adam
  patience: 20
  continue_train: False
test:
  run_times: 1