---
alg: arima
base_dir: log/arima
log_level: INFO
gpu: 0
data: 
  batch_size: 512
  raw_dataset_dir: data/data_load_area.npz
  len_data: 0.8
model:
  seq_len: 24
  horizon: 2
  verified_percentage: 0.8
  num_nodes: 29
test:
  run_times: 10
