---
alg: LSTM
base_dir: log
log_level: INFO
gpu: 0
data:
  batch_size: 512
  raw_dataset_dir: data/data_load_area.npz
  eval_batch_size: 1
  test_batch_size: 1
  data_name: DataLoadArea
  len_data: 0.6
model:
  model_type: ed
  seq_len: 24
  horizon: 2
  input_dim: 1
  verified_percentage: 0.8
  l1_decay: 0
  num_nodes: 29
  output_dim: 1
  rnn_units: 64
  n_rnn_layers: 2
train:
  dropout: 0
  epochs: 50000
  optimizer: adam
  patience: 50
  continue_train: False
test:
  run_times: 50
