---
alg: dcrnn
base_dir: log/dcrnn
log_level: INFO
gpu: 0
data:
  batch_size: 64
  raw_dataset_dir: data/data_load_area.npz
  output_dir: data/dcrnn
  test_batch_size: 1
  val_batch_size: 64
  test_size: 0.6
  graph_pkl_filename: data/dcrnn/adj_mx.pkl

model:
  seq_len: 168
  horizon: 24
  input_dim: 2
  verified_percentage: 0.3
  l1_decay: 0
  num_nodes: 29
  output_dim: 1
  rnn_units: 64 
  cl_decay_steps: 2000
  num_rnn_layers: 2
  filter_type: dual_random_walk
  max_diffusion_step: 2
  use_curriculum_learning: true

train:
  base_lr: 0.01
  dropout: 0
  epoch: 0
  epochs: 50000
  epsilon: 1.0e-3
  global_step: 0
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  optimizer: adam
  patience: 20
  steps: [20, 30, 40, 50]
  test_every_n_epochs: 10
test:
  run_times: 1
  batch_size: 1
