---
alg: lstm_ed
base_dir: log/lstm_ed
log_level: INFO
gpu: 0
data:
  batch_size: 200
  raw_dataset_dir: data/test_data.npz
  eval_batch_size: 1
  test_batch_size: 1
  test_size: 0.2
model:
  model_type: ed
  seq_len: 24
  horizon: 1
  input_dim: 1
  verified_percentage: 1
  l1_decay: 0
  num_nodes: 1
  output_dim: 1
  rnn_units: 100
  num_rnn_layers: 2
train:
  dropout: 0
  epochs: 300
  optimizer: adam
  patience: 50
  continue_train: False
test:
  run_times: 1
